/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_Mp3Encoder
#define _Included_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif

// 初始化 LAME
JNIEXPORT void JNICALL Java_com_encoder_lame_LameNative_init
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

// 交错立体声 encode：pcm 是 short[]（交错 LRLR...），samplesPerChannel 表示每声道的 short 数
JNIEXPORT jint JNICALL Java_com_encoder_lame_LameNative_encodeInterleaved
        (JNIEnv *, jclass, jshortArray, jint, jbyteArray);

// 单声道 encode：pcm 为左声道 short[]
JNIEXPORT jint JNICALL Java_com_encoder_lame_LameNative_encodeMono
        (JNIEnv *, jclass, jshortArray, jint, jbyteArray);

// 直接传 byte[] PCM（little-endian 16-bit），不用在 Java 里转 short[]
// pcmBytes 包含 interleaved 或 单声道数据（由 samplesPerChannel 决定）
// samplesPerChannel 表示每声道的 short 数
JNIEXPORT jint JNICALL Java_com_encoder_lame_LameNative_encodeBytes
        (JNIEnv *, jclass, jbyteArray, jint, jbyteArray);

// flush / close
JNIEXPORT jint JNICALL Java_com_encoder_lame_LameNative_flush
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT void JNICALL Java_com_encoder_lame_LameNative_close
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
